[package]
name = "tiny-chip8"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
spin_sleep = "1.0.0"
rand = "0.8.4"
